package dacn_letrananhnhung;

import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Server_GUI extends javax.swing.JFrame {

    DefaultTableModel model;
    ArrayList<DonHang> dh = new ArrayList();
    TCPServer server = new TCPServer();
    DanhSachDonHang dsdh = new DanhSachDonHang();

    public Server_GUI() {
        initComponents();
        myInit();
    }

    public void myInit() {
        setTitle("Server Quản lý đơn hàng");
        model = (DefaultTableModel) tb_dsdh.getModel();

        tb_dsdh.setModel(model);
        btexit.setEnabled(false);
        inData();
        loadData(dsdh.getDSDH());
    }

    public void addmess(String mess) {
        txt_mess.append(mess + "\n");
    }

    void loadData(ArrayList<DonHang> dh) {
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        for (DonHang x : dh) {
            model.addRow(new Object[]{x.getMaDH(), x.getTenKH(), x.getDiaChi(), x.getTenSP(), x.getDonGia(), x.getSoLuong(), DonHang.dinhDangSo(x.thanhTien()), DonHang.chuyenNgayThanhChuoi(x.getNgayDat()), x.getTrangThai()});
        }
    }

    void inData() {
        try {
            dh = dsdh.inData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(btconnect, e.getMessage());
        }
    }

    public void resetLabel() {
        txtmaDH.setText("");
        txttenKH.setText("");
        txtdiaChi.setText("");
        txttenSP.setText("");
        txtDonGia.setText("");
        txtsoLuong.setText("");
        txtngayDat.setText("");
        txttrangThai.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_dsdh = new javax.swing.JTable();
        panel2 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        txt_port = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_mess = new javax.swing.JTextArea();
        btexit = new javax.swing.JButton();
        btconnect = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        txtmaDH = new javax.swing.JTextField();
        txttenKH = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtdiaChi = new javax.swing.JTextField();
        txttenSP = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtsoLuong = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtngayDat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btedit = new javax.swing.JButton();
        btadd = new javax.swing.JButton();
        btdelete = new javax.swing.JButton();
        txttrangThai = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tb_dsdh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã đơn hàng", "Tên Khách hàng", "Địa chỉ", "Tên sản phẩm", "Đơn giá", "Số lượng", "Thành tiền", "Ngày đặt", "Trạng thái"
            }
        ));
        tb_dsdh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_dsdhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_dsdh);

        jLabel1.setText("Port");

        txt_port.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_portActionPerformed(evt);
            }
        });

        txt_mess.setColumns(20);
        txt_mess.setRows(5);
        jScrollPane2.setViewportView(txt_mess);

        btexit.setText("Exit");
        btexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexitActionPerformed(evt);
            }
        });

        btconnect.setText("Connect");
        btconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btconnectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_port, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addComponent(btexit, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btconnect)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_port, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btexit)
                    .addComponent(btconnect))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );

        txttenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttenKHActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã đơn hàng");

        jLabel3.setText("Tên khách hàng");

        txtDonGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonGiaActionPerformed(evt);
            }
        });

        jLabel4.setText("Địa chỉ");

        jLabel5.setText("Tên sản phẩm");

        txtngayDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtngayDatActionPerformed(evt);
            }
        });

        jLabel6.setText("Đơn giá");

        jLabel7.setText("Số lượng");

        jLabel8.setText("Ngày đặt");

        jLabel9.setText("Trạng thái");

        jLabel11.setText("Thông tin");

        btedit.setText("Edit");
        btedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditActionPerformed(evt);
            }
        });

        btadd.setText("Add");
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });

        btdelete.setText("Delete");
        btdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeleteActionPerformed(evt);
            }
        });

        txttrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttrangThaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtdiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(txtngayDat)
                            .addComponent(txtsoLuong)
                            .addComponent(txtDonGia)
                            .addComponent(txttenSP)
                            .addComponent(txtmaDH)
                            .addComponent(txttenKH)
                            .addComponent(txttrangThai)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btedit, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btadd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btdelete)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(txtmaDH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtdiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtsoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtngayDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txttrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9))))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btedit, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btadd)
                    .addComponent(btdelete))
                .addGap(22, 22, 22))
        );

        jLabel10.setText("ADMIN QUẢN LÝ ĐƠN HÀNG");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_portActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_portActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_portActionPerformed

    private void btexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexitActionPerformed
        try {
            server.Close();
            btexit.setEnabled(false);
            btconnect.setEnabled(true);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(btconnect, e.getMessage());
        }
    }//GEN-LAST:event_btexitActionPerformed

    private void btconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btconnectActionPerformed
        new Thread(() -> {
            int port = 0;
            if (txt_port.getText().isEmpty()) {
                JOptionPane.showMessageDialog(btconnect, "Vui lòng nhập port!");

            } else {
                try {
                    port = Integer.parseInt(txt_port.getText());

                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(btconnect, e.getMessage());
                    addmess("Hãy nhập lại!!!");
                }
                try {
                    btconnect.setEnabled(false);
                    server.connectServer(port);
                    addmess("Server đã sẵn sàng kết nối");
                    btexit.setEnabled(true);
                    try {
                        server.connectClient();
                        addmess("Kết nối thành công");
                        while (true) {
                            String mess, mess1;
                            mess = server.input();
                            addmess("Client: " + mess);
                            if (dsdh.kiemTraTimKiem(mess)) {
                                mess1 = dsdh.timKiemMaDH(mess);
                            } else {
                                mess1 = "Không tìm thấy!";
                            }
                            addmess("Server: " + mess1);
                            server.output(mess1);
                        }

                    } catch (IOException e) {
                        JOptionPane.showMessageDialog(btconnect, e.getMessage());
                        btconnect.setEnabled(true);
                        addmess(e.getMessage());
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(btconnect, e.getMessage());
                    btconnect.setEnabled(true);
                    addmess(e.getMessage());
                }
            }
        }).start();
    }//GEN-LAST:event_btconnectActionPerformed

    private void txttenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttenKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttenKHActionPerformed

    private void txtDonGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonGiaActionPerformed

    private void txtngayDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtngayDatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtngayDatActionPerformed

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed
      try {
            if (dsdh.capNhatDH(txtmaDH.getText(), txttenKH.getText(), txtdiaChi.getText(), txttenSP.getText(), Float.parseFloat(txtDonGia.getText()), Integer.parseInt(txtsoLuong.getText()), DonHang.chuyenChuoiThanhNgay(txtngayDat.getText()), txttrangThai.getText())) {
                for(DonHang x: dh){
                    if(x.getMaDH().equalsIgnoreCase(txtmaDH.getText())){
                        x.setTenKH(txttenKH.getText());
                        x.setDiaChi(txtdiaChi.getText());
                        x.setTenSP(txttenSP.getText());
                        x.setDonGia(Float.parseFloat(txtDonGia.getText()));
                        x.setSoLuong(Integer.parseInt(txtsoLuong.getText()));
                        x.setNgayDat(DonHang.chuyenChuoiThanhNgay(txtngayDat.getText()));
                        x.setTrangThai(txttrangThai.getText());
                    }
                }
                loadData(dsdh.getDSDH());
                resetLabel();
                addmess("Đã sửa thành công");
            } else {
                addmess("Mã đơn hàng không tồn tại");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(btedit, e);
            addmess(e.getMessage());
        } 
    }//GEN-LAST:event_bteditActionPerformed

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddActionPerformed
        try {
            if (dsdh.themMoi(txtmaDH.getText(), txttenKH.getText(), txtdiaChi.getText(), txttenSP.getText(), Float.parseFloat(txtDonGia.getText()), Integer.parseInt(txtsoLuong.getText()), DonHang.chuyenChuoiThanhNgay(txtngayDat.getText()), txttrangThai.getText())) {
                loadData(dsdh.getDSDH());
                resetLabel();
                addmess("Đã thêm thành công");
            } else {
                addmess("Mã đơn hàng đã tồn tại");
            }
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(btadd, e);
            addmess(e.getMessage());
        }
    }//GEN-LAST:event_btaddActionPerformed

    private void btdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeleteActionPerformed
        String madh = txtmaDH.getText();
        try {
            if(dsdh.xoaDH(madh)){
                for(DonHang x: dh){
                    if(x.getMaDH().equalsIgnoreCase(madh)){
                        dh.remove(x);
                    }
                }
                loadData(dsdh.getDSDH());
                resetLabel();
                addmess("Đã xóa thành công");
            }
            else{
                addmess("Mã đơn hàng không tồn tại");
            }
            
        } catch (SQLException e) {
        JOptionPane.showMessageDialog(btdelete, e.getMessage());
        addmess(e.getMessage());
        }    
    }//GEN-LAST:event_btdeleteActionPerformed

    private void txttrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttrangThaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttrangThaiActionPerformed

    private void tb_dsdhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_dsdhMouseClicked
        DefaultTableModel model = (DefaultTableModel) tb_dsdh.getModel();
        int selectedRow = tb_dsdh.getSelectedRow();
        txtmaDH.setText(model.getValueAt(selectedRow, 0).toString());
        txttenKH.setText(model.getValueAt(selectedRow, 1).toString());
        txtdiaChi.setText(model.getValueAt(selectedRow, 2).toString());
        txttenSP.setText(model.getValueAt(selectedRow, 3).toString());
        txtDonGia.setText(model.getValueAt(selectedRow, 4).toString());
        txtsoLuong.setText(model.getValueAt(selectedRow, 5).toString());
        txtngayDat.setText(model.getValueAt(selectedRow, 7).toString());
        txttrangThai.setText(model.getValueAt(selectedRow, 8).toString());    
    }//GEN-LAST:event_tb_dsdhMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadd;
    private javax.swing.JButton btconnect;
    private javax.swing.JButton btdelete;
    private javax.swing.JButton btedit;
    private javax.swing.JButton btexit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private javax.swing.JTable tb_dsdh;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextArea txt_mess;
    private javax.swing.JTextField txt_port;
    private javax.swing.JTextField txtdiaChi;
    private javax.swing.JTextField txtmaDH;
    private javax.swing.JTextField txtngayDat;
    private javax.swing.JTextField txtsoLuong;
    private javax.swing.JTextField txttenKH;
    private javax.swing.JTextField txttenSP;
    private javax.swing.JTextField txttrangThai;
    // End of variables declaration//GEN-END:variables
}
