package dacn_letrananhnhung;

import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Server_GUI extends javax.swing.JFrame {

    DefaultTableModel model;
    ArrayList<DonHang> dh = new ArrayList();
    TCPServer server = new TCPServer();
    DanhSachDonHang dsdh = new DanhSachDonHang();

    public Server_GUI() {
        initComponents();
        myInit();
        txtmaDH.setEnabled(false);
    }

    public void myInit() {
        setTitle("Server Quản lý đơn hàng");
        model = (DefaultTableModel) tb_dsdh.getModel();
        tb_dsdh.setModel(model);
        btexit.setEnabled(false);
        inData();
        loadData(dsdh.getDSDH());

        new Thread(() -> {
            int port = 2004;
            try {
                server.connectServer(port);
                addmess("Server đã sẵn sàng kết nối");
                btexit.setEnabled(true);

                try {
                    server.connectClient();
                    addmess("Kết nối thành công");
                    boolean running = true;
                    while (running) {
                        String mess, mess1;
                        mess = server.input();
                        addmess("Client: " + mess);
                        if (mess.startsWith("maDH:")) {
                            String searchQuery = mess.substring(6); // Extract the search query
                            List<DonHang> donHangList = dsdh.timKiemMaDH(searchQuery);
                            if (!donHangList.isEmpty()) {
                                StringBuilder sb = new StringBuilder();
                                for (DonHang dh : donHangList) {
                                    sb.append(dh.toString()).append(";");
                                }
                                mess1 = sb.toString();
                            } else {
                                mess1 = "Không tìm thấy!";
                            }
                        } else if (mess.startsWith("trangThai:")) {
                            String searchQuery = mess.substring(10); // Extract the search query
                            List<DonHang> donHangList = dsdh.timKiemTheoTrangThai(searchQuery);
                            if (!donHangList.isEmpty()) {
                                StringBuilder sb = new StringBuilder();
                                for (DonHang dh : donHangList) {
                                    sb.append(dh.toString()).append(";");
                                }
                                mess1 = sb.toString();
                            } else {
                                mess1 = "Không tìm thấy!";
                            }
                        } else {
                            mess1 = "Yêu cầu không hợp lệ!";
                        }
                        addmess("Server: " + mess1);
                        server.output(mess1);
                    }

                } catch (IOException e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                    addmess(e.getMessage());
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
                addmess(e.getMessage());
            }
        }).start();
    }

    public void addmess(String mess) {
        txt_mess.append(mess + "\n");
    }

    void loadData(ArrayList<DonHang> dh) {
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        for (DonHang x : dh) {
            model.addRow(new Object[]{x.getMaDH(), x.getTenKH(), x.getDiaChi(), x.getTenSP(), x.getDonGia(),
                x.getSoLuong(), DonHang.dinhDangSo(x.thanhTien()), DonHang.chuyenNgayThanhChuoi(x.getNgayDat()),
                x.getTrangThai()});
        }
    }

    void inData() {
        try {
            dh = dsdh.inData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void resetLabel() {
        txtmaDH.setText("");
        txttenKH.setText("");
        txtdiaChi.setText("");
        txttenSP.setText("");
        txtDonGia.setText("");
        txtsoLuong.setText("");
        txtngayDat.setText("");
        txttrangThai.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_dsdh = new javax.swing.JTable();
        panel2 = new java.awt.Panel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_mess = new javax.swing.JTextArea();
        btexit = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        txtmaDH = new javax.swing.JTextField();
        txttenKH = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtdiaChi = new javax.swing.JTextField();
        txttenSP = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtsoLuong = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtngayDat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btedit = new javax.swing.JButton();
        btadd = new javax.swing.JButton();
        btdelete = new javax.swing.JButton();
        txttrangThai = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tb_dsdh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã đơn hàng", "Tên Khách hàng", "Địa chỉ", "Tên sản phẩm", "Đơn giá", "Số lượng", "Thành tiền", "Ngày đặt", "Trạng thái"
            }
        ));
        tb_dsdh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_dsdhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_dsdh);

        txt_mess.setColumns(20);
        txt_mess.setRows(5);
        jScrollPane2.setViewportView(txt_mess);

        btexit.setText("Disconnect");
        btexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(btexit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btexit)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );

        txttenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttenKHActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã đơn hàng");

        jLabel3.setText("Tên khách hàng");

        txtDonGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonGiaActionPerformed(evt);
            }
        });

        jLabel4.setText("Địa chỉ");

        jLabel5.setText("Tên sản phẩm");

        txtngayDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtngayDatActionPerformed(evt);
            }
        });

        jLabel6.setText("Đơn giá");

        jLabel7.setText("Số lượng");

        jLabel8.setText("Ngày đặt");

        jLabel9.setText("Trạng thái");

        jLabel11.setText("Thông tin");

        btedit.setText("Edit");
        btedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditActionPerformed(evt);
            }
        });

        btadd.setText("Add");
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });

        btdelete.setText("Delete");
        btdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeleteActionPerformed(evt);
            }
        });

        txttrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttrangThaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9)
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7))
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(39, 39, 39)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtdiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(txtngayDat)
                            .addComponent(txtsoLuong)
                            .addComponent(txtDonGia)
                            .addComponent(txttenSP)
                            .addComponent(txtmaDH)
                            .addComponent(txttenKH)
                            .addComponent(txttrangThai)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btedit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(btadd, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 50, Short.MAX_VALUE))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmaDH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(9, 9, 9)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(12, 12, 12)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtngayDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(16, 16, 16)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btedit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btdelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel10.setText("ADMIN QUẢN LÝ ĐƠN HÀNG");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(52, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_portActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_portActionPerformed
        // TODO add your handling code here:
    }

    private void txttenKHActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txttenKHActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txttenKHActionPerformed

    private void txtDonGiaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtDonGiaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtDonGiaActionPerformed

    private void txtngayDatActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtngayDatActionPerformed
        // TODO add your handling code here:
    }

    private void txttrangThaiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txttrangThaiActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtngayDatActionPerformed

    private void tb_dsdhMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tb_dsdhMouseClicked
        DefaultTableModel model = (DefaultTableModel) tb_dsdh.getModel();
        int selectedRow = tb_dsdh.getSelectedRow();
        txtmaDH.setText(model.getValueAt(selectedRow, 0).toString());
        txttenKH.setText(model.getValueAt(selectedRow, 1).toString());
        txtdiaChi.setText(model.getValueAt(selectedRow, 2).toString());
        txttenSP.setText(model.getValueAt(selectedRow, 3).toString());
        txtDonGia.setText(model.getValueAt(selectedRow, 4).toString());
        txtsoLuong.setText(model.getValueAt(selectedRow, 5).toString());
        txtngayDat.setText(model.getValueAt(selectedRow, 7).toString());
        txttrangThai.setText(model.getValueAt(selectedRow, 8).toString());
    }

    private void btexitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btexitActionPerformed
        try {
            server.Close();
            btexit.setEnabled(false);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bteditActionPerformed
        try {
            String maDH = txtmaDH.getText();
            String tenKH = txttenKH.getText();
            String diaChi = txtdiaChi.getText();
            String tenSP = txttenSP.getText();
            float donGia = Float.parseFloat(txtDonGia.getText());
            int soLuong = Integer.parseInt(txtsoLuong.getText());
            Date ngayDat = DonHang.chuyenChuoiThanhNgay(txtngayDat.getText());
            String trangThai = txttrangThai.getText();
            if (dsdh.edit(maDH, tenKH, diaChi, tenSP, donGia, soLuong, ngayDat, trangThai)) {
                loadData(dsdh.getDSDH());
                resetLabel();
                addmess("Đã sửa thành công");
            } else {
                addmess("Mã đơn hàng không tồn tại");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(btedit, "Lỗi định dạng số: " + e.getMessage());
            addmess("Lỗi định dạng số: " + e.getMessage());
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(btedit, "Lỗi định dạng ngày: " + e.getMessage());
            addmess("Lỗi định dạng ngày: " + e.getMessage());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(btedit, e.getMessage());
            addmess(e.getMessage());
        }
    }// GEN-LAST:event_bteditActionPerformed

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btaddActionPerformed
        try {
            String tenKH = txttenKH.getText();
            String diaChi = txtdiaChi.getText();
            String tenSP = txttenSP.getText();
            float donGia = Float.parseFloat(txtDonGia.getText());
            int soLuong = Integer.parseInt(txtsoLuong.getText());
            Date ngayDat = DonHang.chuyenChuoiThanhNgay(txtngayDat.getText());
            String trangThai = txttrangThai.getText();
            if (dsdh.themMoi(tenKH, diaChi, tenSP, donGia, soLuong, ngayDat, trangThai) == true) {
                loadData(dsdh.getDSDH());
                resetLabel();
                addmess("Đã thêm thành công");
            } else {
                addmess("Lỗi khi thêm đơn hàng");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(btadd, "Lỗi định dạng số: " + e.getMessage());
            addmess("Lỗi định dạng số: " + e.getMessage());
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(btadd, "Lỗi định dạng ngày: " + e.getMessage());
            addmess("Lỗi định dạng ngày: " + e.getMessage());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(btadd, e.getMessage());
            addmess(e.getMessage());
        }
    }// GEN-LAST:event_btaddActionPerformed

    private void btdeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btdeleteActionPerformed
        String madh = txtmaDH.getText();
        try {
            if (dsdh.delete(madh)) {
                loadData(dsdh.getDSDH());
                resetLabel();
                addmess("Đã xóa thành công");
            } else {
                addmess("Mã đơn hàng không tồn tại");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(btdelete, e.getMessage());
            addmess(e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadd;
    private javax.swing.JButton btdelete;
    private javax.swing.JButton btedit;
    private javax.swing.JButton btexit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private javax.swing.JTable tb_dsdh;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextArea txt_mess;
    private javax.swing.JTextField txtdiaChi;
    private javax.swing.JTextField txtmaDH;
    private javax.swing.JTextField txtngayDat;
    private javax.swing.JTextField txtsoLuong;
    private javax.swing.JTextField txttenKH;
    private javax.swing.JTextField txttenSP;
    private javax.swing.JTextField txttrangThai;
    // End of variables declaration//GEN-END:variables
}
